# Generated by Django 5.0.10 on 2024-12-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_ministerio"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="nome",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
