# Generated by Django 5.1.3 on 2024-12-05 02:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="noticia",
            old_name="texto",
            new_name="conteudo",
        ),
        migrations.RemoveField(
            model_name="noticia",
            name="data",
        ),
        migrations.RemoveField(
            model_name="noticia",
            name="foto",
        ),
        migrations.RemoveField(
            model_name="noticia",
            name="hora",
        ),
        migrations.RemoveField(
            model_name="noticia",
            name="local",
        ),
        migrations.RemoveField(
            model_name="noticia",
            name="tema",
        ),
        migrations.AddField(
            model_name="noticia",
            name="data_publicacao",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="noticia",
            name="imagem",
            field=models.ImageField(
                default="noticias/default.jpg", upload_to="noticias/"
            ),
        ),
        migrations.AddField(
            model_name="noticia",
            name="subtitulo",
            field=models.CharField(default="Subtítulo padrão", max_length=300),
        ),
        migrations.AddField(
            model_name="noticia",
            name="titulo",
            field=models.CharField(default="Titulo padrão", max_length=200),
        ),
    ]
