# Generated by Django 5.1.3 on 2024-12-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_texto_noticia_conteudo_remove_noticia_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefone", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
            ],
        ),
    ]
