# Generated by Django 5.1.3 on 2024-12-14 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_contato"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="igreja",
            name="lideres",
        ),
        migrations.RemoveField(
            model_name="igreja",
            name="membros",
        ),
        migrations.AlterField(
            model_name="igreja",
            name="pastor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pastor_igreja",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ministerio",
            name="membros",
            field=models.ManyToManyField(
                related_name="ministerios", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="igreja",
            name="lideres",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lideres_igreja",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="igreja",
            name="membros",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membros_igreja",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
